{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 59,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "from torch.autograd import Variable\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import numpy as np\n",
    "import database as db\n",
    "from torchvision import transforms\n",
    "import matplotlib.pyplot as plt\n",
    "from torch.utils.data import DataLoader\n",
    "import itertools\n",
    "import random\n",
    "import time"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Discriminator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [],
   "source": [
    "class GANdiscriminator(nn.Module):\n",
    "    ''' This class implements a PatchGAN discriminator for a 100x100 image.\n",
    "        Small modification of the one used in:\n",
    "            - Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks \n",
    "              Jun-Yan Zhu, 2017'''\n",
    "    \n",
    "    def __init__(self, n_image_channels = 3):\n",
    "        super(GANdiscriminator, self).__init__()\n",
    "                \n",
    "        def createLayer(n_filt_in, n_filt_out, ker_size, stride, norm = True, last = False):\n",
    "            ''' This function creates the differnt convolutional layers, all with same structure'''\n",
    "            layers = [nn.Conv2d(n_filt_in, n_filt_out, ker_size, stride=stride)]\n",
    "            if (norm):\n",
    "                layers.append(nn.InstanceNorm2d(n_filt_out)) # batch normalization\n",
    "            if (last):\n",
    "                layers.append(nn.Sigmoid()) # we output the probability\n",
    "            else:\n",
    "                layers.append(nn.LeakyReLU(negative_slope = 0.05, inplace=True)) # we use Leaky ReLU\n",
    "            return layers\n",
    "        \n",
    "        \n",
    "        ''' Input number of filters: Image channels\n",
    "            Intermediate number of filters: 64*h, with h being the depth of the layer\n",
    "            Output number of filters: 1 -> Decision of true or false\n",
    "            It takes patches of 61x61 pixels'''\n",
    "        layers = []\n",
    "        n_layers = 5\n",
    "        ker_size = 5\n",
    "        strides = [1, 1, 1, 2, 2]\n",
    "        n_filters = [n_image_channels, 64, 128, 256, 512, 1]\n",
    "        lasts = [False, False, False, False, True]\n",
    "        for i in range(n_layers): # For each layer\n",
    "            layers.extend(createLayer(n_filters[i], n_filters[i+1], ker_size, strides[i], last = lasts[i]))\n",
    "                \n",
    "        self.model = nn.Sequential(*layers)\n",
    "        \n",
    "    \n",
    "    def forward(self, image):\n",
    "        return self.model(image)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Generator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [],
   "source": [
    "class residual_block(nn.Module):\n",
    "    ''' This class implements the residual block of the RES net we will implement as the generator'''\n",
    "    def __init__(self, n_channels):\n",
    "        super(residual_block, self).__init__()\n",
    "        \n",
    "        layers = [ \n",
    "                  nn.ReflectionPad2d(1), # mirroring of 1 for the 3 kernel size convolution\n",
    "                  nn.Conv2d(n_channels, n_channels, 3), # the convolution :)\n",
    "                  nn.InstanceNorm2d(n_channels), # batch normalization\n",
    "                  nn.LeakyReLU(negative_slope=0.05, inplace=True), \n",
    "                  # We repeat the process\n",
    "                  nn.ReflectionPad2d(1), \n",
    "                  nn.Conv2d(n_channels, n_channels, 3),\n",
    "                  nn.InstanceNorm2d(n_channels)\n",
    "                 ]\n",
    "        \n",
    "        self.conv_block = nn.Sequential(*layers)\n",
    "    \n",
    "    def forward(self, image):\n",
    "        return image + self.conv_block(image)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "class GANgenerator(nn.Module):\n",
    "    ''' This class implements a RES Net for generating the images\n",
    "        Small modification of the one defined in:\n",
    "            - Deep Residual Learning for Image Recognition\n",
    "              Kaiming He, 2015'''\n",
    "    \n",
    "    def __init__(self, n_image_channels = 3, n_res_blocks = 9):\n",
    "        super(GANgenerator, self).__init__()\n",
    "        \n",
    "        ''' High kernel convolution '''\n",
    "        n_channels_high = 64\n",
    "        layers = [ nn.ReflectionPad2d(3), # mirroring of 3 for the 7 kernel size convolution\n",
    "                    nn.Conv2d(n_image_channels, n_channels_high, 7), # 64 new channels of 7x7 convolution :)\n",
    "                    nn.InstanceNorm2d(n_channels_high),\n",
    "                    nn.LeakyReLU(negative_slope=0.05, inplace=True)\n",
    "                  ]\n",
    "        \n",
    "        ''' Variables for down and up sampling '''\n",
    "        n_layers = 2\n",
    "        ker_size = 3\n",
    "        strides = 2\n",
    "        paddings = 1\n",
    "        n_filters = [n_channels_high, n_channels_high*2, n_channels_high*4]\n",
    "        \n",
    "        ''' Downsampling steps '''\n",
    "        for i in range(n_layers): # for each layer\n",
    "            layers.extend([ nn.Conv2d(n_filters[i], n_filters[i+1], ker_size, \\\n",
    "                                    strides, padding=paddings),\n",
    "                            nn.InstanceNorm2d(n_filters[i+1]),\n",
    "                            nn.LeakyReLU(negative_slope=0.05, inplace=True)])\n",
    "        \n",
    "        ''' Residual blocks '''\n",
    "        for i in range(n_res_blocks):\n",
    "            layers.extend([residual_block(n_filters[-1])]) # the residual blocks are applied to the \n",
    "                                                           # last number of channels in the down sampling\n",
    "        \n",
    "        ''' Upsampling steps '''\n",
    "        for i in range(n_layers): # for each layer\n",
    "            layers.extend([ nn.ConvTranspose2d(n_filters[-(i+1)], n_filters[-(i+2)], ker_size, \\\n",
    "                                    strides, padding=paddings, output_padding=1),\n",
    "                            nn.InstanceNorm2d(n_filters[-(i+2)]),\n",
    "                            nn.LeakyReLU(negative_slope=0.05, inplace=True)])\n",
    "        ''' Output '''\n",
    "        layers.extend([ nn.ReflectionPad2d(3), # mirroring of 3 for the 7 kernel size convolution\n",
    "                        nn.Conv2d(n_channels_high, n_image_channels, 7), # 64 new channels of 7x7 convolution :)\n",
    "                        nn.Sigmoid() ])\n",
    "                \n",
    "        self.res_net = nn.Sequential(*layers)\n",
    "        \n",
    "    def forward(self, image):\n",
    "        return self.res_net(image)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Training"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Losses\n",
    "criterion_gan = nn.BCELoss()\n",
    "criterion_cycle = nn.L1Loss()\n",
    "criterion_identity = nn.L1Loss()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Prepare for using cuda or not\n",
    "cuda = True if torch.cuda.is_available() else False # for using the GPU if possible"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Calculate the number of patches (61x61) separated 25\n",
    "batch_size = 1\n",
    "img_x = 128\n",
    "img_y = 128\n",
    "separation = 25\n",
    "patch_x, patch_y = 26, 26\n",
    "patch = (batch_size, 1 , patch_x, patch_y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generation of the discriminator and generator\n",
    "D_A = GANdiscriminator()\n",
    "D_B = GANdiscriminator()\n",
    "G_AB = GANgenerator()\n",
    "G_BA = GANdiscriminator()\n",
    "if cuda:\n",
    "    D_A = D_A.cuda()\n",
    "    D_B = D_B.cuda()\n",
    "    G_AB = G_AB.cuda()\n",
    "    G_BA = G_BA.cuda()\n",
    "    criterion_gan.cuda()\n",
    "    criterion_cycle.cuda()\n",
    "    criterion_identity.cuda()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Initialize weights\n",
    "def weights_init(m):\n",
    "    classname = m.__class__.__name__\n",
    "    if classname.find('Conv') != -1:\n",
    "        torch.nn.init.kaiming_normal(m.weight.data, a=0.05)\n",
    "    elif classname.find('BatchNorm2d') != -1:\n",
    "        torch.nn.init.kaiming_normal(m.weight.data, a=0.05)\n",
    "        torch.nn.init.constant_(m.bias.data, 0.0)\n",
    "\n",
    "G_AB.apply(weights_init); # He initialization of the weights\n",
    "G_BA.apply(weights_init); # He initialization of the weights\n",
    "D_A.apply(weights_init); # He initialization of the weights\n",
    "D_B.apply(weights_init); # He initialization of the weights"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define the optimizer for the generator\n",
    "lr = 1e-4\n",
    "beta_1 = 0.9\n",
    "beta_2 = 0.99\n",
    "gan_params = list(G_AB.parameters()) + list(G_BA.parameters())\n",
    "optimizer_G = torch.optim.Adam(gan_params, lr = lr, betas=(beta_1, beta_2))\n",
    "optimizer_D_A = torch.optim.Adam(D_A.parameters(), lr=lr, betas=(beta_1, beta_2))\n",
    "optimizer_D_B = torch.optim.Adam(D_B.parameters(), lr=lr, betas=(beta_1, beta_2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [],
   "source": [
    "class lr_update():\n",
    "    def __init__(self, n_epochs, epoch, start_decay_epoch):\n",
    "        assert ((n_epochs - start_decay_epoch) > 0), \"You can't decay after finishing\"\n",
    "        self.n_epochs = n_epochs\n",
    "        self.epoch = epoch\n",
    "        self.start_decay_epoch = start_decay_epoch\n",
    "    \n",
    "    def decay(self, epoch):\n",
    "        return 1.0 - max(0, epoch + self.epoch - self.start_decay_epoch) \\\n",
    "            / (self.n_epochs - self.start_decay_epoch)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Scheduler for optimization\n",
    "n_epochs = 250\n",
    "epoch = 0\n",
    "start_decay_epoch = 100\n",
    "\n",
    "lr_scheduler_G = torch.optim.lr_scheduler.LambdaLR(optimizer_G, \\\n",
    "    lr_lambda=lr_update(n_epochs, epoch, start_decay_epoch).decay)\n",
    "lr_scheduler_D_A = torch.optim.lr_scheduler.LambdaLR(optimizer_D_A, \\\n",
    "    lr_lambda=lr_update(n_epochs, epoch, start_decay_epoch).decay)\n",
    "lr_scheduler_D_B = torch.optim.lr_scheduler.LambdaLR(optimizer_D_B, \\\n",
    "    lr_lambda=lr_update(n_epochs, epoch, start_decay_epoch).decay)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Structure for using cuda tensors or just cpu tensors\n",
    "Tensor = torch.cuda.FloatTensor if cuda else torch.Tensor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "metadata": {},
   "outputs": [],
   "source": [
    "# class to store the images\n",
    "class imageBuffer():\n",
    "    def __init__(self, max_size = 50):\n",
    "        assert (max_size > 0), 'You need to be able to store something'\n",
    "        self.max_size = max_size\n",
    "        self.data = []\n",
    "    \n",
    "    def push_and_pop(self, data):\n",
    "        result = []\n",
    "        for element in data.data:\n",
    "            element = torch.unsqueeze(element, 0)\n",
    "            # If we can store data\n",
    "            if len(self.data) < self.max_size:\n",
    "                self.data.append(element)\n",
    "                result.append(element)\n",
    "            # Else change a random element of the data with probability 0.5\n",
    "            else:\n",
    "                if random.uniform(0,1) > 0.5:\n",
    "                    pos = random.randint(0, self.max_size-1)\n",
    "                    result.append(self.data[pos].clone())\n",
    "                    self.data[i] = element\n",
    "                else:\n",
    "                    result.append(element)\n",
    "        # Return the result as a torch variable\n",
    "        return Variable(torch.cat(result))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 78,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Buffers of previously generated samples \n",
    "fake_A_buffer = imageBuffer()\n",
    "fake_B_buffer = imageBuffer()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Prepare the data\n",
    "fruits_file = 'Dataset/dataset_index.csv'\n",
    "textures_file = 'Dataset/textures_index.csv'\n",
    "textures = db.TexturesDataset(csv_file=textures_file)\n",
    "train_imgs_A = db.FruitsDataset(csv_file=fruits_file, cl='Strawberry', \n",
    "                        transform = transforms.Compose(\n",
    "                            [db.ChangeBackground(textures),\n",
    "                             db.myReshape()]))\n",
    "train_imgs_B = db.FruitsDataset(csv_file=fruits_file, cl='Orange', \n",
    "                        transform = transforms.Compose(\n",
    "                            [db.ChangeBackground(textures),\n",
    "                             db.myReshape()]))\n",
    "dataloader_A = DataLoader(train_imgs_A, batch_size=batch_size,\n",
    "                        shuffle=True, num_workers=1)\n",
    "\n",
    "dataloader_B = DataLoader(train_imgs_B, batch_size=batch_size,\n",
    "                        shuffle=True, num_workers=1)\n",
    "val_dataloader_A = DataLoader(train_imgs_A, batch_size=5,\n",
    "                        shuffle=True, num_workers=1)\n",
    "val_dataloader_B = DataLoader(train_imgs_B, batch_size=5,\n",
    "                        shuffle=True, num_workers=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sample_images(num_batches):\n",
    "    ''' Saves a generated sample from the validation set'''\n",
    "    img_A = next(iter(val_dataloader_A))\n",
    "    img_B = next(iter(val_dataloader_B))\n",
    "    real_A = Variable(img_A.type(Tensor))\n",
    "    fake_B = G_AB(real_A)\n",
    "    real_B = Variable(img_B.type(Tensor))\n",
    "    fake_A = G_BA(real_B)\n",
    "    ## Gudardar-les després és cosa d'en Marcel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "##########################################################\n",
      "- EPOCH: 0\n",
      "##########################################################\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7f3da9f01b00>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 250, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 246, in _shutdown_workers\n",
      "    self.index_queue.put(None)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 355, in put\n",
      "    self._writer.send_bytes(obj)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 200, in send_bytes\n",
      "    self._send_bytes(m[offset:offset + size])\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 404, in _send_bytes\n",
      "    self._send(header + buf)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 368, in _send\n",
      "    n = write(self._handle, buf)\n",
      "OSError: [Errno 9] Bad file descriptor\n",
      "Process Process-348:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.5/multiprocessing/process.py\", line 249, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\", line 36, in _worker_loop\n",
      "    r = index_queue.get()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/queues.py\", line 343, in get\n",
      "    res = self._reader.recv_bytes()\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/usr/lib/python3.5/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-86-1b678cb8b276>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     11\u001b[0m         \u001b[0;31m# Get Model input\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     12\u001b[0m         \u001b[0mreal_A\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mVariable\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mbatch_A\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mTensor\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 13\u001b[0;31m         \u001b[0mreal_B\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mVariable\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnext\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0miter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdataloader_B\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mTensor\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\u001b[0m in \u001b[0;36m__iter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    308\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    309\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__iter__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 310\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mDataLoaderIter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    311\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    312\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__len__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, loader)\u001b[0m\n\u001b[1;32m    165\u001b[0m             \u001b[0;32mfor\u001b[0m \u001b[0mw\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mworkers\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    166\u001b[0m                 \u001b[0mw\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdaemon\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m  \u001b[0;31m# ensure that the worker exits on process exit\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 167\u001b[0;31m                 \u001b[0mw\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstart\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    168\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    169\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpin_memory\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/multiprocessing/process.py\u001b[0m in \u001b[0;36mstart\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    103\u001b[0m                \u001b[0;34m'daemonic processes are not allowed to have children'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    104\u001b[0m         \u001b[0m_cleanup\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 105\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_popen\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_Popen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    106\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sentinel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_popen\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msentinel\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    107\u001b[0m         \u001b[0m_children\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/multiprocessing/context.py\u001b[0m in \u001b[0;36m_Popen\u001b[0;34m(process_obj)\u001b[0m\n\u001b[1;32m    210\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mstaticmethod\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    211\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_Popen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess_obj\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 212\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0m_default_context\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_context\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mProcess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_Popen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess_obj\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    213\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    214\u001b[0m \u001b[0;32mclass\u001b[0m \u001b[0mDefaultContext\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mBaseContext\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/multiprocessing/context.py\u001b[0m in \u001b[0;36m_Popen\u001b[0;34m(process_obj)\u001b[0m\n\u001b[1;32m    265\u001b[0m         \u001b[0;32mdef\u001b[0m \u001b[0m_Popen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess_obj\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    266\u001b[0m             \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mpopen_fork\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mPopen\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 267\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mPopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess_obj\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    268\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    269\u001b[0m     \u001b[0;32mclass\u001b[0m \u001b[0mSpawnProcess\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mBaseProcess\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/multiprocessing/popen_fork.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, process_obj)\u001b[0m\n\u001b[1;32m     18\u001b[0m         \u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstderr\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mflush\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     19\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreturncode\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 20\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_launch\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprocess_obj\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     21\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     22\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mduplicate_for_child\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfd\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/lib/python3.5/multiprocessing/popen_fork.py\u001b[0m in \u001b[0;36m_launch\u001b[0;34m(self, process_obj)\u001b[0m\n\u001b[1;32m     65\u001b[0m         \u001b[0mcode\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m         \u001b[0mparent_r\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mchild_w\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpipe\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpid\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfork\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpid\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "# Training phase\n",
    "\n",
    "start_time = time.time()\n",
    "\n",
    "for epoch in range(n_epochs):\n",
    "    print(\"##########################################################\")\n",
    "    print(\"- EPOCH: \" + str(epoch))\n",
    "    print(\"##########################################################\")\n",
    "    for i, batch_A in enumerate(dataloader_A):\n",
    "        \n",
    "        # Get Model input\n",
    "        real_A = Variable(batch_A.type(Tensor))\n",
    "        real_B = Variable(next(iter(dataloader_B)).type(Tensor))\n",
    "        \n",
    "        \n",
    "        '''\n",
    "        # Get model input\n",
    "        input_img = Variable(batch.type(Tensor))\n",
    "        \n",
    "        #Generator \n",
    "        \n",
    "        # Set the optimizer\n",
    "        optimizer_G.zero_grad()\n",
    "        \n",
    "        # Create some noise\n",
    "        noise = Variable(Tensor(np.random.normal(loc = 0.0, \\\n",
    "            scale= 0.5, size=batch.shape)))\n",
    "    \n",
    "        # Generate some images from the noise\n",
    "        generated = G(noise)\n",
    "        \n",
    "        # See how well they do\n",
    "        loss_g = criterion(D(generated),valid)\n",
    "        \n",
    "        # We use backpropagation\n",
    "        loss_g.backward(retain_graph=True)\n",
    "        \n",
    "        # And make ADAM do its shit\n",
    "        optimizer_G.step()\n",
    "        \n",
    "        # Discriminator \n",
    "        \n",
    "        # Set the optimizer\n",
    "        optimizer_D.zero_grad()\n",
    "        \n",
    "        loss_d_real = criterion(D(input_img),valid)\n",
    "        loss_d_fake = criterion(D(generated),fake)\n",
    "        loss_d = 0.5 * (loss_d_real + loss_d_fake)\n",
    "        \n",
    "        # We use backpropagation\n",
    "        loss_d.backward(retain_graph=True)\n",
    "        \n",
    "        # We let ADAM do its shit\n",
    "        optimizer_D.step()\n",
    "        \n",
    "        print(\"Image #: \" + str(i*batch_size))\n",
    "        \n",
    "        '''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    " # Create some noise\n",
    "noise = Tensor(np.random.normal(loc = 0.0, \\\n",
    "    scale= 0.9, size=batch.shape))\n",
    "\n",
    "noise = Tensor(np.zeros(batch.shape))\n",
    "\n",
    "# Generate some images from the noise\n",
    "generated = G(noise)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(128, 128, 3)"
      ]
     },
     "execution_count": 42,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "v = generated[1].data.cpu().numpy()\n",
    "v = np.transpose(v, (2,1,0))\n",
    "v.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAksAAAJCCAYAAADQsoPKAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMi4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvhp/UCwAAIABJREFUeJzs3X1w1f153/nrOofbNsiynrjNw202OCGpC20lm4Mbys5uGxMQTohNElLT3dbtZNbLTpFANl07LZ20O2FqZrawaXcnLW0enAekWGBs41gIJyTTack63DiZ8GCcgGRibukIQWKiGPNwn993/7i1iOv6fvNFIAmdyO/XTMe+fr/f+Zzv7zjT852ji+unIQQBAABAWmm+FwAAAFDP2CwBAABksFkCAADIYLMEAACQwWYJAAAgg80SAABABpslAACADDZLAAAAGXO2WVLVTlX9mqpeU9VPzNX7AAAAzCWdiwneqloWkT8SkR8UkZsicl5EdoUQrqSuX6oaVucCGxLHvpVfw4X1tl6fvsy9yJaFOz2dneVXXL1I/oap/9b6y9FrHsk6U4/Km0097q5/R+J9R13d5Oo/nUbGLVc3PiVj5TQy/DruuHpFIsPfLxlkkEEGGd9ZGasSGc/6PfeKxPsb/z73Lnzldgjh5cTbGYuedsFzeq+IXAshDImIqGqfiHxARJKbpdUi8mourSNx7L/Z0n8kJReYzHcvCm439G13+eJEhLp6iaub5bOmPn9+bZRxS06a+l/L95j659z1H0v8H8C/civpdOf7XL0vkfHvXMb73PlfdfXeaDsp8rNuS7nNnf+Uq/9pIuP/cRk/5M7/EhlkkEEGGQs646cSGT/jvqN+qLD1r5bs99rH5FGU4b/HXi295UZ0UcJc/RnuFRH5xhP1zcljj6nqR1T1VVV91e84AQAA6sW8NXiHEI6GECohhMpTf/8CAACYJ3P1Z7jXxP7J8R2Tx9LWi/07mfvblro/uaX41qvC1er/XpZ4H/+jn/+zm/97qIjI2+W+qV+Xt9h1yRpTl+zpN9z/XlP6nwn9n+F+M/EHwbvuj4YfljeZuk8emnpQvivK+IbYXyN/3N3LL7t7/Q15Z5QxIsOm/oBb6y+6df6mfHeUMSpD2YxfcBm/NQsZs7EOMsgggwwyZifjtGtHERGpynVT/73SUlP/Srht6hv6rijja+Fr0bHpmKtfls6LyPeq6jtV9U0i8iER+fwcvRcAAMCcmZNflkIIr6vqHhEZFJGyiPxCCCH+Z2AAAAB1bq7+DCchhC+KyBfnKh8AAOBFmLPN0rOqPdFj9Gb3z9pfCnHD0QP/T99fsnXpoX9NnFFEXUr2mrI7G4pUhu0N8n/YXOLe4/333xplXNW/MPUHnzL66r8mjrlVyCVX+8i7idEBLe7+//ApGaVZyEgd8Rl/8AIylAwyyCCDjLrJiLuIRZrcF+wl16z8yDUnj0gtymh0X+MT8lJ0TQqPOwEAAMhgswQAAJDBZgkAACCDzRIAAEDGnDxI91lV1mt49dwTB9zgRo37vKQo2YPqHuwW3VZqKKVrKdMftheF30i9JlqJX5jNcNvRdyRa6qt2XmTUkuYbzeOn3cQN3v6aN7t6NPGBrHB752+5e3ur+7y+mthrv8vlPi3jaiLjr5FBBhlkkPEdnfG1RMZa92/SRl3GKpfx+/4LWEQ2ug3G7fLEhRBCJbrQ4ZclAACADDZLAAAAGWyWAAAAMupjKKVK3FTzhJBqWnrKPq/kWnJCapRh2fUo+WYh39ZTJNZRcj1K7rTvN6o9jDPGXcfRl+Suy7QPHPy+eBXyNlf/z09Zxz9KZHyX65b6X92rFrm760lkvDPKsP8n5jP2JTJWu4yPkEEGGWSQ8R2V8dFExjLXjdvtMsou418nepXbgn1g7+3o2zONX5YAAAAy2CwBAABksFkCAADIqI+eJRHT7BN1F2m8p/NH/Fwl/8zbTYmepXOuRyl+Tq7rLyo9fR1uzJLU3DP6mhP70wlX97m/oar7W++/kQ1Rxt+X86beKdtMfVwGTL1dPhxldMmnTP2v5P2mPiZfNPUPyI9FGV+UE6b+F9LpMk6b+n3yo4mMz5j6gLuXXncvZJBBBhlkLLSM7XFGOGXq98pOU39Ojpv63e68iMhn3XfUdPHLEgAAQAabJQAAgAw2SwAAABn10bN0Qey2rXDPbPNDk0SkcNf4wUol18RUJB8Ol5rflDmd2FoWT7koPLDn78qDKOMlN2TKzypSN+/otXgZ0RylocQ15nzimYCL9BdN/XXX51Vyn+FryQxbf92d9xl/QgYZZJBBBhkuYziRUVJ7bCjY79dCj5n6Nb9PEJE3lX7FHckMeTTrAwAAwF+KzRIAAEAGmyUAAIAMNksAAAAZGhJNVC9apaLh/KtTddTPnXyOrmvsCnbfV8r3f0/Guibw4JrE3fWJ2ZiyyC3unptK2eCHVL4eZ9TUtmc/VNvgbR+jKzIRtXOLNLqm8D931zS5dY6FOGO5e99bwfb/LxO7+BuJdfx3LmPMZSxXm/H1EP8bg+9y15BBBhlkkPGdlXE9uInOIvJ97po/DG81dcX9A6qz4S1Rxt9Te82fl+9fCCFUogsdflkCAADIYLMEAACQwWYJAAAgoz6GUoqYcVRj7tzLiX4j9cMfn5KfaBUScT1KL7n38UO0HiaT7Toa3Vn/miLRPPXQ/c/wX+SGqVXebup9rj9JRGSp2L/vftQN+LJ/2RXZm2gEe9m95uPumre5pq1/luh3e7urP+H+l3mb+7z+WeJ/OTLIIIMMMr6zM34q8R3V7Or/w32zL3YZ/0afnvHnsiS6JoVflgAAADLYLAEAAGSwWQIAAMioj56lByIyPFW+7M8ne5Ys/5fJv3B1PBEoalmSInof3xsUp7zFvfP9kt1/ftNd/8qb4r/l3n5g5z6c0e81tcq3Tf1jYUWU8Ysyaur18hOm/oXQb+r36o9EGZ8uPm/qv647TT1Rsxnv0R+OM8IXTP0u/TGXccKus/RDUUZ/8RtkkEEGGWR8B2e8R98fZZwIp13Gh0z9+fAZU7cnMr4UfiM6Nh38sgQAAJDBZgkAACCDzRIAAEBGffQsXRIJ3/3kAdvXExJNS0Xhen/UzRUqbC9ROcT7wkeJGQw5b0oc83OUfEfSW11P080Hcd/TD6tNeSncNXWDNpn6S4l1l9z/lJfcQsqlY6a+ETdoRc++G3KfcalsM0aeK8OeJ4MMMsgggwyfcTPx9RzUvuZacBfpfzLlnyS+98vR9ydzlgAAAGaMzRIAAEAGmyUAAIAMNksAAAAZGhIPQ33RKqrh1Sdqv6K1iddcicZQlrLlX/IkXfeaxPTLp8qvw59t1fg9Hj6yzdm31C7WP+D2Zoj78l/RRzbDDdB82Q3YrCYGbK5w14y7e1nqGuNGE81zK90dj7v3War2PUZDvI6Vz7yOF5UxG/dCBhlkkEHG0zK+kfiee6fL+EP3iPiK2AHPp0NDlLFFv2XqifKDCyGESnShwy9LAAAAGWyWAAAAMtgsAQAAZNTHUMr1InL+idpt4a4U9kGyb1zjLnLtR4tc/XrUPSRxj9JT2qDiCxIXuUsa3Tr/rHQ/Sriqzab+PX27qV+Sr5p6e1gcZfheqI+6XrRmNxFsrx/qKSIt7vPodgO/Wt297kv0u7W4j6PbXfPiMhbSvZBBBhlkfGdl7PcDJ0Xkbe7/X/+XhR3o7L9vjwTb4yQi0uzeZ0Li79MUflkCAADIYLMEAACQwWYJAAAgoz56li6I27a5v1X6/iQRKbnZQ8Wb7d8/X7//ZveK+O+fi9yh15/aoxR/XEvcAKd7JTvX4a7+halHHrwtyvjb7u+q/z7YmUmPpMXU/1g3RhldxX8z9btlu6l/tThl6g7dFmX8ejFg6nbZYere4qTNKM1GRmci4zQZZJBBBhnfyRkaZxwvzpj6r8s/MPVAcdzUa9V+D4qInA6nomPTwS9LAAAAGWyWAAAAMtgsAQAAZNRHz5KUJMgTvT6P3OmX4lcUi9z8hIf2OTNL1M5m+lbiOTP3owfG2bpW2Loox7MjJtx+s+YW/9rrtrdKwzeijMVq+5hOB/vsmjeX7PNvvlbEz5cruzlL1/1j79zax2pxhm8NG/YZJXvgVkhkuENDT1nHrcS9kEEGGWSQ8Z2dUU18R2nJ9hF/3c9i0v9oytTzS19S34u8JLomhV+WAAAAMtgsAQAAZLBZAgAAyGCzBAAAkKEh8cC7F61S0fB7TzxIt+yaoiv+qbgiciHYhu4J17T1Vvdk3TMSN4ttFzswcqKwwx8Xu63kFxMP9vsR18j2R/IWU69xD8797ShB5H9U20g+HGxH+/eobRr/eqJZfbW7Zryw17xcsg3xqca3lWKvGRf7GS91n/FsZFQTGctdxm0yyCCDDDK+ozJupr7nXMbFYP/xU0UfmPp0iJu3f1DvmXqi/OBCCKESXejwyxIAAEAGmyUAAIAMNksAAAAZdTGUMsh6eSRTTUttpavm/O/Ju6LXrFL7UL6XpNPVD039dxKTLd8q32fqj5bsMMjvcj1K/33i77Df5QY1vsWdf5tbx8nE32Ffdj1Lx9yAyWaxDwX+l1GCSLOr96pdV5vbF/cketWa3dSwrsLef5s+PaPlGTP2JTJaZyFjNtZBBhlkkEHG/GR8LNEj3OgyDgT7/fpW9z132PU4iYg0u2smZHF0TQq/LAEAAGSwWQIAAMhgswQAAJBRFz1LIl+R8hN9OX9a2JlBDzXuNxpxD6yd0NWmfl2+buqvyw9GGXfluqn31F4x9X8q/Zmpb8qbooyvB7uO6/Ieu65w3tTvLr0zyvj3wa7jLfIjdp3F5039N0sbo4xfKX7X1O3yY6buLU7Y8yXb4yUi0lfYPrAO+VF7vvYZl7EtkTHgMna4jJNkkEEGGWSQkc3o0DjjeDFo6rXyD0w9EI7b87o9yjgdvhAdmw5+WQIAAMhgswQAAJDBZgkAACCjLnqWXpf3yNgTvT0NblVfSsxbKLmZDL/ongWn7llwn5F47sMid82/dTOTFrnHyX0pXoaU3Hazt7AZL9nH38itED+jzj+27o/cUstle+BmEWf4dQy7tZZcxlgqwx0adut4noyhWciYjXWQQQYZZJDxVydjtBZnaMl+sX3d7w30P9qMxGzEl9R/kcfPj0vhlyUAAIAMNksAAAAZbJYAAAAy2CwBAABkaEg88O5FW1/R8OUnZjf60Y/VxJ5updgmrQl3TaM7/2fiOq1FpMU9ZO9Pgx1+2aZ24OR4EffDv909BPeOe1BuW8mev1XE63i72nXccWttc+erIc5Y7u7ltstY6praqonGNzLIIIMMMsioh4ybiYfOr3YZF0ODqStqH6x7OsTN2z+o90w9UX5wIYRQiS50+GUJAAAgg80SAABAxnNvllR1lar+tqpeUdXLqrp38nirqn5JVf948j9bZm+5AAAAL9ZMhlK+LiIfCyF8RVUbReSCqn5JRP6xiPxWCOGTqvoJEfmEiHw8FzQm6+WITDUtvcWd/0TiNQ1uyOQBN9nRP3r3f0kMpWxy9c+4PqcWt5f8mCYy1L7v/qdkdCfW0eIyut2grVaXsS/RZ9biJn51FS5D5yeju07WQQYZZJBBxl+djP2JYdSNLuOAe5B9g9sHHHE9TiIize77dEIWR9ekPPcvSyGE0RDCVyb/+4SIfFVEXhGRD4jIpyYv+5SIfPB53wMAAGC+zUrPkqquFpF3i8iXRWRZCGF08lRVRJb9Ja/5iKq+qqqvfmt8fDaWAQAAMOtmvFlS1beKyAkR2RdC+PMnz4U35hIkZxOEEI6GECohhErDyy/PdBkAAABzYkYP0lXVl+SNjdKvhRA+M3l4TFVXhBBGVXWFiNx6Wk6TXJJOedfj+qfCH5nz36Md0Wv+Qv7A1H9T/qGpXw+/Yur3yY4o4zPyWVN/t+w09d1av6nfVdocZfxK8ZumXicfMvUvFX2mfo++P8roK75o6nb5UVMfKz5jz5e2JTIGTN3h7revdnJeMtpdxrFZWEcvGWSQQQYZCztD44z+YtDUa2WXqQfCCXtet0cZA+EL0bHpmMm/hlMR+XkR+WoI4fATpz4vIh+e/O8fFpHPPe97AAAAzLeZ/LK0SUT+oYhcVNX//2eefy4inxSRT6vqT4rIDRH5iZktEQAAYP4892YphPBfRdy/05vyvufNBQAAqCcz6lmaLfflb8iVJ+Ysld0W7JbE8xYWuX3a77o28pL+kqkvJdrM/ftc9BnlY6YeKeK9Ydn9IfOPCn/e9k7dDHGGGx0h192MipJ7FFw1sQ6fMRzdiz0wNgsZt1IZ7vMY9p8HGWSQQQYZZDwlY7SW+C2mZF90w89i0qOmHEk8o26R+v1E/Py4FB53AgAAkMFmCQAAIIPNEgAAQAabJQAAgAwNiQfevWjvrmj4nfNT+7alrqF7KMR96GvUPiBv3O37lroH6FWD65IWkeXufcbFXvOye4/RRMZK9z633DVvdxmvJTJe0XzGyyW/jniPu8Ldy23/ebimtmoiY7m7l9vu83iejDsuo40MMsgggwwynpJxM/G9v9plXAoNpl6vD009GOLm7c16z9QT5QcXQgiV6EKHX5YAAAAy2CwBAABksFkCAADIqIuhlFVZL5+U33tcL3bnfyYxm6rJ9ej8b27f91Y3tHJfYrBlq8vd6/q3Wl3mxxL9XS1uu+kz2tS+yccSLWJ+Hd1u0FabW0dPKsNNlOwqbEar2ox9yXuZ/Yw9ZJBBBhlkkPGMGfv9wEkRaXQZ/yI8MnWD+749HGyPk4hIs/s+nYh2HGn8sgQAAJDBZgkAACCDzRIAAEBGXfQsvU0uS6e0P67/bbhkzr9D/070mm+G3zX19+vfN3V/8eum3qCdUUZfcdrU7fKjpu4tPmPqv1XaGmX0FoMuY4c9Xztpz09jHR3yQXu+9lmbUdqWyBhwGU9ZxyxkdJBBBhlkkEHGHGS0a5zR775v18ouUw8UJ+x53R5lDIRT0bHp4JclAACADDZLAAAAGWyWAAAAMuqiZ+m+rJOvhak5S26UgowlZjb4ay4He6Bc+jVTX0/MJiq5reJ1N9ahVLYvqhbxwCc31kGG3VrL7j2SGSX7miG31pJ7nNxYIsN/HsMuo+zu5VYqw6112H0ePiO5DjLIIIMMMsiYYcZoLTFgsWRfdMPPYtKjphxJPKNukfr5TfHz41L4ZQkAACCDzRIAAEAGmyUAAIAMNksAAAAZGhLN0y9aR0XD2fNT+7Zl7qG3QyHuQ1+j9gF5466Ra6k7Xw2uS1pElou95rbYa6aTscKt9Za75u0u4zWJM16Rp9yLa2qrJprW/L3cce/TpvOTEX+mZJBBBhlkkJHPuJn43l/tMi6GBlNX9KGpB0PcvL1Z75l6ovzgQgihEl3o8MsSAABABpslAACADDZLAAAAGXUxlLIq6+WQTA2lXCK2j+pgYjZVk+sV2q1239co9kU9Evdmtbrcbte/1er2kj2J/q5mNw1yrxuS1eqmVn7Mz8MSkRa3ZfXraHPr2JdYR4tbx57Cr2N+MrrIIIMMMsgg4xkz9vuBkyLS6DIOhEembnDft4eD7XESEWl236cTsji6JoVflgAAADLYLAEAAGSwWQIAAMioi56lJrksndL+uD4SLpnzq3RT9Jq74ZypN+pOUx8v+k1d0S1RRm9xxtTtssOdP2nPl7YmMgbzGTWXoZ2JjNMu44Mu47NuHduijL5iwNQdT1vHLGR01Mk6yCCDDDLIWGAZGmf0u+/btbLL1APFCXtet0cZA+EL0bHp4JclAACADDZLAAAAGWyWAAAAMuqiZ+m+rJOrYWrOkhulIKOJmQ1unIJcKeyBcqnX1NcSj8Arua3ikBvrUCrbF42590hlDBf2NWV3vhoSGe7QkLvfknuc3K1prcPWZXcvs5Exvc9j7teRzHCHht3//mSQQQYZZNRvxmgtMWDRPSf1hp/FpEdNOZJ4Rt0i9fOb4ufHpfDLEgAAQAabJQAAgAw2SwAAABlslgAAADI0JJqnX7SOioaz56e6mJeJffjdUIj70NeovWbcNXItdefHguuSTrzPbbHX+IxqImOF+HW4DNeQNprIWOkzxN+LzagmmtaWu4w77l7a5ikj/kzJIIMMMsggI59xM/G9v9plXAwNpq7oQ1MPhrh5e7PeM/VE+cGFEEIlutDhlyUAAIAMNksAAAAZbJYAAAAy6mIoZVXWyyGZGkq5RGwf1cHEbKomsX/f3K1239co9kX7JO7NanW53a5/q9XtJXsS/V3NbtJWtxuS1ebW0ZNoEWtxW9YuN9iyzd3bvsQ6Wtw69hR2Ha3zlNFFBhlkkEEGGc+Ysd8PnBSRRpdxIDwydYObVn042B4nEZFm970+IYuja1L4ZQkAACCDzRIAAEAGmyUAAICMuuhZapLL0intj+sj4ZI5v0o3Ra+5G86ZeqPuNPXxot/UFd0SZfQWZ0zdLjtMfaw4ac+XtiYyBrMZvTWb0aGdUUZfcdpe4zL6an4d2xIZA9kMv47ZyOiok4x6+TzIIIMMMsiYpQyNM/rd9+1a2WXqgeKEPa/bo4yBcCo6Nh38sgQAAJDBZgkAACCDzRIAAEBGXfQs3Zd1cjVMzVlyoxRkJDGzwY1TkCuFPVAu9Zr6WmK+UcltFa+7sQ7lsn3RmHuPVMawm5FUduerIZHhDg25+y25x8ndmtY6bO3vZTYykp+HOzTsPvfn+0zzGfXyeZBBBhlkkDE7GaO1xIBF96zVG34Wkx415UjiGXWL1M9vip8fl8IvSwAAABlslgAAADLYLAEAAGSwWQIAAMjQkGieftE6KhrOnp/qYl4m9uF3QyHuQ1+j9ppx18i11J0fC65LOvE+t8Ve4zOqiYwV4tfhMlxD2mgiY6XPEH8vNqOaaFpb7jLuuHtpm6eM+DMlgwwyyCCDjHzGzcT3/mqXcTE0mLqiD009GOLm7c16z9QT5QcXQgiV6EKHX5YAAAAy2CwBAABksFkCAADIqIuhlFVZL4dkaijlErF9VAcTs6maxP59c7fafV+j2Bftlbg3q9Xldrv+rVa3l+xJ9Hc1uymM3W5IVptbR0+iRazFbVm73GDLNndv+xLraHHr2FPYdbTOU0YXGWSQQQYZZDxjxn4/cFJEGl3GgfDI1A1uWvXhYHucRESa3ff6hCyOrknhlyUAAIAMNksAAAAZbJYAAAAy6qJnqUkuS6e0P66PhEvm/CrdFL3mbjhn6o2609THi35Tb9AtUUZfccbU7bLD1MeKk/Z8aWuU0VsMZjN6azajQzsT6zhtr3EZfTW/jm2JjIFshl/HbGR01Mk6yCCDDDLIWGAZGmf0u+/btbLL1APFCXtet0cZA+FUdGw6+GUJAAAgg80SAABABpslAACAjLroWbov6+RqmJqz5EYpyEhiZoMbpyBXCnugXOo19bXEfKOS2yped2MdymX7ojH3HqmMYTcjqezOV0Miwx0acvdbco+TuzWtddja38tsZCQ/D3do2H3uc7EOMsgggwwyFlbGaC0xYNE9a/WGn8WkR005knhG3SL185vi58el8MsSAABABpslAACADDZLAAAAGWyWAAAAMjQkmqdftI6KhrPnp7qYl4l9+N1QiPvQ16i9Ztw1ci1158eC65JOvM9tsdf4jGoiY4X4dbgM15A2mshY6TPE34vNqCaa1pa7jDvuXtrmKSP+TMkggwwyyCAjn3Ez8b2/2mVcDA2mruhDUw+GuHl7s94z9UT5wYUQQiW60OGXJQAAgAw2SwAAABkz3iypallVf19VvzBZv1NVv6yq11T111X1TTNfJgAAwPyYjaGUe0XkqyLytsn6kIgcCSH0qep/EJGfFJGfywVUZb0ckqmhlEvE9lEdTMymahL7983davd9jWJftFfi3qxWl9vt+rda3V6yJ9Hf1eymMHa7IVltbh09iRaxFrdl7XKDLdvcve1LrKPFrWNPYdfROk8ZXWSQQQYZZJDxjBn7/cBJEWl0GQfCI1M3uGnVh4PtcRIRaXbf6xOyOLomZUa/LKnqO0Tkh0TkP0/WKiI/ICLHJy/5lIh8cCbvAQAAMJ9m+me4/0tE/neRxz/ztInIN0MIr0/WN0XkldQLVfUjqvqqqr767fHxGS4DAABgbjz3ZklVf1hEboUQLjzP60MIR0MIlRBCZfHLLz/vMgAAAObUTHqWNonIj6jq+0XkLfJGz9LPikizqi6a/HXpHSLy2tOCmuSydEr74/pIuGTOr9JN0WvuhnOm3qg7TX286Df1Bt0SZfQVZ0zdLjtMfaw4ac+XtkYZvcVgNqO3ZjM6tDOxjtP2GpfRV/Pr2JbIGMhm+HXMRkZHnayDDDLIIIOMBZahcUa/+75dK7tMPVCcsOd1e5QxEE5Fx6bjuX9ZCiH8VAjhHSGE1SLyIRE5G0L4n0Tkt0Xkxycv+7CIfO553wMAAGC+zcWcpY+LyEdV9Zq80cP083PwHgAAAC/EbIwOkBDC74jI70z+9yERee9s5AIAAMy3WdkszdR9WSdXw9ScJTdKQUYSMxvcOAW5UtgD5VKvqa8l5huV3O9q191Yh3LZvmjMvUcqY9jNSCq789WQyHCHhtz9ltzj5G5Nax229vcyGxnJz8MdGnaf+1ysgwwyyCCDjIWVMVpLDFh0z1q94Wcx6VFTjiSeUbdI/fym+PlxKTzuBAAAIIPNEgAAQAabJQAAgAw2SwAAABkaEs3TL1pHRcPZ81NdzMvEPvxuKMR96GvUXjPuGrmWuvNjwXVJJ97ntthrfEY1kbFC/DpchmtIG01krPQZ4u/FZlQTTWvLXcYddy9t85QRf6ZkkEEGGWSQkc+4mfjeX+0yLoYGU1f0oakHQ9y8vVnvmXqi/OBCCKESXejwyxIAAEAGmyUAAIAMNksAAAAZdTGUsirr5ZBMDaVcIraP6mBiNlWT2L9v7la772sU+6K9Evdmtbrcbte/1er2kj2J/q5mN4Wx2w3JanPr6Em0iLW4LWuXG2zZ5u5tX2IdLW4dewq7jtZ5yugigwwyyCCDjGfM2O8HTopIo8s4EB6ZusFNqz4cbI+TiEiz+16fkMXRNSn8sgQAAJDBZgkAACCDzRIAAEBGXfQsNcll6ZT2x/WRcMmcX6WbotdaPTTKAAAgAElEQVTcDedMvVF3mvp40W/qDbolyugrzpi6XXaY+lhx0p4vbY0yeovBbEZvzWZ0aGdiHaftNS6jr+bXsS2RMZDN8OuYjYyOOlkHGWSQQQYZCyxD44x+9327VnaZeqA4Yc/r9ihjIJyKjk0HvywBAABksFkCAADIYLMEAACQURc9S/dlnVwNU3OW3CgFGUnMbHDjFORKYQ+US72mvpaYb1RyW8XrbqxDuWxfNObeI5Ux7GYkld35akhkuEND7n5L7nFyt6a1Dlv7e5mNjOTn4Q4Nu899LtZBBhlkkEHGwsoYrSUGLLpnrd7ws5j0qClHEs+oW6R+flP8/LgUflkCAADIYLMEAACQwWYJAAAgg80SAABAhoZE8/SL1lHRcPb8VBfzMrEPvxsKcR/6GrXXjLtGrqXu/FhwXdKJ97kt9hqfUU1krBC/DpfhGtJGExkrfYb4e7EZ1UTT2nKXccfdS9s8ZcSfKRlkkEEGGWTkM24mvvdXu4yLocHUFX1o6sEQN29v1numnig/uBBCqEQXOvyyBAAAkMFmCQAAIIPNEgAAQEZdDKWsyno5JFNDKZeI7aM6mJhN1ST275u71e77GsW+aK/EvVmtLrfb9W+1ur1kT6K/q9lNYex2Q7La3Dp6Ei1iLW7L2uUGW7a5e9uXWEeLW8eewq6jdZ4yusgggwwyyCDjGTP2+4GTItLoMg6ER6ZucNOqDwfb4yQi0uy+1ydkcXRNCr8sAQAAZLBZAgAAyGCzBAAAkFEXPUtNclk6pf1xfSRcMudX6aboNXfDOVNv1J2mPl70m3qDboky+oozpm6XHaY+Vpy050tbo4zeYjCb0VuzGR3amVjHaXuNy+ir+XVsS2QMZDP8OmYjo6NO1kEGGWSQQcYCy9A4o999366VXaYeKE7Y87o9yhgIp6Jj08EvSwAAABlslgAAADLYLAEAAGTURc/SfVknV8PUnCU3SkFGEjMb3DgFuVLYA+VSr6mvJeYbldxW8bob61Au2xeNufdIZQy7GUlld74aEhnu0JC735J7nNytaa3D1v5eZiMj+Xm4Q8Puc5+LdZBBBhlkkLGwMkZriQGL7lmrN/wsJj1qypHEM+oWqZ/fFD8/LoVflgAAADLYLAEAAGSwWQIAAMhgswQAAJChIdE8/aJ1VDScPT/VxbxM7MPvhkLch75G7TXjrpFrqTs/FlyXdOJ9bou9xmdUExkrxK/DZbiGtNFExkqfIf5ebEY10bS23GXccffSNk8Z8WdKBhlkkEEGGfmMm4nv/dUu42JoMHVFH5p6MMTN25v1nqknyg8uhBAq0YUOvywBAABksFkCAADIYLMEAACQURdDKauyXg7J1FDKJWL7qA4mZlM1if375m61+75GsS/aK3FvVqvL7Xb9W61uL9mT6O9qdlMYu92QrDa3jp5Ei1iL27J2ucGWbe7e9iXW0eLWsaew62idp4wuMsgggwwyyHjGjP1+4KSINLqMA+GRqRvctOrDwfY4iYg0u+/1CVkcXZPCL0sAAAAZbJYAAAAy2CwBAABk1EXPUpNclk5pf1wfCZfM+VW6KXrN3XDO1Bt1p6mPF/2m3qBbooy+4oyp22WHqY8VJ+350tYoo7cYzGb01mxGh3Ym1nHaXuMy+mp+HdsSGQPZDL+O2cjoqJN1kEEGGWSQscAyNM7od9+3a2WXqQeKE/a8bo8yBsKp6Nh08MsSAABABpslAACADDZLAAAAGXXRs3Rf1snVMDVnyY1SkJHEzAY3TkGuFPZAudRr6muJ+UYlt1W87sY6lMv2RWPuPVIZw25GUtmdr4ZEhjs05O635B4nd2ta67C1v5fZyEh+Hu7QsPvc52IdZJBBBhlkLKyM0VpiwKJ71uoNP4tJj5pyJPGMukXq5zfFz49L4ZclAACADDZLAAAAGWyWAAAAMtgsAQAAZGhINE+/aB0VDWfPT3UxLxP78LuhEPehr1F7zbhr5Frqzo8F1yWdeJ/bYq/xGdVExgrx63AZriFtNJGx0meIvxebUU00rS13GXfcvbTNU0b8mZJBBhlkkEFGPuNm4nt/tcu4GBpMXdGHph4McfP2Zr1n6onygwshhEp0ocMvSwAAABlslgAAADLYLAEAAGTUxVDKqqyXQzI1lHKJ2D6qg4nZVE1i/765W+2+r1Hsi/ZK3JvV6nK7Xf9Wq9tL9iT6u5rdFMZuNySrza2jJ9Ei1uK2rF1usGWbu7d9iXW0uHXsKew6Wucpo4sMMsgggwwynjFjvx84KSKNLuNAeGTqBjet+nCwPU4iIs3ue31CFkfXpPDLEgAAQAabJQAAgAw2SwAAABl10bPUJJelU9of10fCJXN+lW6KXnM3nDP1Rt1p6uNFv6k36JYoo684Y+p22WHqY8VJe760NcroLQazGb01m9GhnYl1nLbXuIy+ml/HtkTGQDbDr2M2MjrqZB1kkEEGGWQssAyNM/rd9+1a2WXqgeKEPa/bo4yBcCo6Nh38sgQAAJDBZgkAACCDzRIAAEBGXfQs3Zd1cjVMzVlyoxRkJDGzwY1TkCuFPVAu9Zr6WmK+UcltFa+7sQ7lsn3RmHuPVMawm5FUduerIZHhDg25+y25x8ndmtY6bO3vZTYykp+HOzTsPve5WAcZZJBBBhkLK2O0lhiw6J61esPPYtKjphxJPKNukfr5TfHz41L4ZQkAACCDzRIAAEAGmyUAAIAMNksAAAAZGhLN0y9aR0XD2fNTXczLxD78bijEfehr1F4z7hq5lrrzY8F1SSfe57bYa3xGNZGxQvw6XIZrSBtNZKz0GeLvxWZUE01ry13GHXcvbfOUEX+mZJBBBhlkkJHPuJn43l/tMi6GBlNX9KGpB0PcvL1Z75l6ovzgQgihEl3o8MsSAABABpslAACAjBltllS1WVWPq+pVVf2qqm5U1VZV/ZKq/vHkf7bM1mIBAABetJkOpfxZETkdQvhxVX2TvDHd6Z+LyG+FED6pqp8QkU+IyMdzIVVZL4dkaijlErF9VAcTs6maxP59c7fafV+j2Bftlbg3q9Xldrv+rVa3l+xJ9Hc1uymM3W5IVptbR0+iRazFbVm73GDLNndv+xLraHHr2FPYdbTOU0YXGWSQQQYZZDxjxn4/cFJEGl3GgfDI1A1uWvXhYHucRESa3ff6hCyOrkl57l+WVLVJRP4HEfl5EZEQwsMQwjdF5AMi8qnJyz4lIh983vcAAACYbzP5M9w7RWRcRH5RVX9fVf+zqjaIyLIQwujkNVURWZZ6sap+RFVfVdVXvz0+PoNlAAAAzJ2ZbJYWich7ROTnQgjvFpFvyRt/cnssvDGXIDmbIIRwNIRQCSFUFr/88gyWAQAAMHdm0rN0U0RuhhC+PFkflzc2S2OquiKEMKqqK0Tk1tOCmuSydEr74/pIuGTOr9JN0WvuhnOm3qg7TX286Df1Bt0SZfQVZ0zdLjtMfaw4ac+XtkYZvcVgNqO3ZjM6tDOxjtP2GpfRV/Pr2JbIGMhm+HXMRkZHnayDDDLIIIOMBZahcUa/+75dK7tMPVCcsOd1e5QxEE5Fx6bjuX9ZCiFUReQbqvrXJg+9T0SuiMjnReTDk8c+LCKfe973AAAAmG8z/ddwXSLya5P/Em5IRP6JvLEB+7Sq/qSI3BCRn5jhewAAAMybGW2WQgh/ICKpMeHvm0kuAABAvZjpL0uz4r6sk6thas6SG6UgI4mZDW6cglwp7IFyqdfU1xJt5iX3R8jrbqxDuWxfNObeI5Ux7GYkld35akhkuEND7n5L7nFyt6a1Dlv7e5mNjOTn4Q4Nu899LtZBBhlkkEHGwsoYrSUGLLpnrd7ws5j0qClHEs+oW6R+flP8/LgUHncCAACQwWYJAAAgg80SAABABpslAACADA2J5ukXraOi4ez5qS7mZWIffjcU4j70NWqvGXeNXEvd+bHguqQT73Nb7DU+o5rIWCF+HS7DNaSNJjJW+gzx92IzqommteUu4467l7Z5yog/UzLIIIMMMsjIZ9xMfO+vdhkXQ4OpK/rQ1IMhbt7erPdMPVF+cCGEkPpX/Qa/LAEAAGSwWQIAAMhgswQAAJBRF0Mpq7JeDsnUUMolYvuoDiZmUzWJ/fvmbrX7vkaxL9orcW9Wq8vtdv1brW4v2ZPo72p2Uxi73ZCsNreOnkSLWIvbsna5wZZt7t72JdbR4taxp7DraJ2njC4yyCCDDDLIeMaM/X7gpIg0uowD4ZGpG9y06sPB9jiJiDS77/UJWRxdk8IvSwAAABlslgAAADLYLAEAAGTURc9Sk1yWTml/XB8Jl8z5Vbopes3dcM7UG3WnqY8X/abeoFuijL7ijKnbZYepjxUn7fnS1iijtxjMZvTWbEaHdibWcdpe4zL6an4d2xIZA9kMv47ZyOiok3WQQQYZZJCxwDI0zuh337drZZepB4oT9rxujzIGwqno2HTwyxIAAEAGmyUAAIAMNksAAAAZddGzdF/WydUwNWfJjVKQkcTMBjdOQa4U9kC51Gvqa4n5RiW3VbzuxjqUy/ZFY+49UhnDbkZS2Z2vhkSGOzTk7rfkHid3a1rrsLW/l9nISH4e7tCw+9znYh1kkEEGGWQsrIzRWmLAonvW6g0/i0mPmnIk8Yy6RernN8XPj0vhlyUAAIAMNksAAAAZbJYAAAAy2CwBAABkaEg0T79oHRUNZ89PdTEvE/vwu6EQ96GvUXvNuGvkWurOjwXXJZ14n9tir/EZ1UTGCvHrcBmuIW00kbHSZ4i/F5tRTTStLXcZd9y9tM1TRvyZkkEGGWSQQUY+42bie3+1y7gYGkxd0YemHgxx8/ZmvWfqifKDCyGESnShwy9LAAAAGWyWAAAAMtgsAQAAZNTFUMqqrJdDMjWUconYPqqDidlUTWL/vrlb7b6vUeyL9krcm9Xqcrtd/1ar20v2JPq7mt0Uxm43JKvNraMn0SLW4rasXW6wZZu7t32JdbS4dewp7Dpa5ymjiwwyyCCDDDKeMWO/HzgpIo0u40B4ZOoGN636cLA9TiIize57fUIWR9ek8MsSAABABpslAACADDZLAAAAGXXRs9Qkl6VT2h/XR8Ilc36VbopeczecM/VG3Wnq40W/qTfoliijrzhj6nbZYepjxUl7vrQ1yugtBrMZvTWb0aGdiXWctte4jL6aX8e2RMZANsOvYzYyOupkHWSQQQYZZCywDI0z+t337VrZZeqB4oQ9r9ujjIFwKjo2HfyyBAAAkMFmCQAAIIPNEgAAQEZd9Czdl3VyNUzNWXKjFGQkMbPBjVOQK4U9UC71mvpaYr5RyW0Vr7uxDuWyfdGYe49UxrCbkVR256shkeEODbn7LbnHyd2a1jps7e9lNjKSn4c7NOw+97lYBxlkkEEGGQsrY7SWGLDonrV6w89i0qOmHEk8o26R+vlN8fPjUvhlCQAAIIPNEgAAQAabJQAAgAw2SwAAABkaEs3TL1pHRcPZ81NdzMvEPvxuKMR96GvUXjPuGrmWuvNjwXVJJ97ntthrfEY1kbFC/DpchmtIG01krPQZ4u/FZlQTTWvLXcYddy9t85QRf6ZkkEEGGWSQkc+4mfjeX+0yLoYGU1f0oakHQ9y8vVnvmXqi/OBCCKESXejwyxIAAEAGmyUAAIAMNksAAAAZdTGUsirr5ZBMDaVcIraP6mBiNlWT2L9v7la772sU+6K9Evdmtbrcbte/1er2kj2J/q5mN4Wx2w3JanPr6Em0iLW4LWuXG2zZ5u5tX2IdLW4dewq7jtZ5yugigwwyyCCDjGfM2O8HTopIo8s4EB6ZusFNqz4cbI+TiEiz+16fkMXRNSn8sgQAAJDBZgkAACCDzRIAAEBGXfQsNcll6ZT2x/WRcMmcX6WbotfcDedMvVF3mvp40W/qDbolyugrzpi6XXaY+lhx0p4vbY0yeovBbEZvzWZ0aGdiHaftNS6jr+bXsS2RMZDN8OuYjYyOOlkHGWSQQQYZCyxD44x+9327VnaZeqA4Yc/r9ihjIJyKjk0HvywBAABksFkCAADIYLMEAACQURc9S/dlnVwNU3OW3CgFGUnMbHDjFORKYQ+US72mvpaYb1RyW8XrbqxDuWxfNObeI5Ux7GYkld35akhkuEND7n5L7nFyt6a1Dlv7e5mNjOTn4Q4Nu899LtZBBhlkkEHGwsoYrSUGLLpnrd7ws5j0qClHEs+oW6R+flP8/LgUflkCAADIYLMEAACQwWYJAAAgg80SAABAhoZE8/SL1lHRcPb8VBfzMrEPvxsKcR/6GrXXjLtGrqXu/FhwXdKJ97kt9hqfUU1krBC/DpfhGtJGExkrfYb4e7EZ1UTT2nKXccfdS9s8ZcSfKRlkkEEGGWTkM24mvvdXu4yLocHUFX1o6sEQN29v1numnig/uBBCqEQXOvyyBAAAkMFmCQAAIIPNEgAAQEZdDKWsyno5JFNDKZeI7aM6mJhN1ST275u71e77GsW+aK/EvVmtLrfb9W+1ur1kT6K/q9lNYex2Q7La3Dp6Ei1iLW7L2uUGW7a5e9uXWEeLW8eewq6jdZ4yusgggwwyyCDjGTP2+4GTItLoMg6ER6ZucNOqDwfb4yQi0uy+1ydkcXRNCr8sAQAAZLBZAgAAyGCzBAAAkFEXPUtNclk6pf1xfSRcMudX6aboNXfDOVNv1J2mPl70m3qDboky+oozpm6XHaY+Vpy050tbo4zeYjCb0VuzGR3amVjHaXuNy+ir+XVsS2QMZDP8OmYjo6NO1kEGGWSQQcYCy9A4o999366VXaYeKE7Y87o9yhgIp6Jj08EvSwAAABlslgAAADLYLAEAAGTURc/SfVknV8PUnCU3SkFGEjMb3DgFuVLYA+VSr6mvJeYbldxW8bob61Au2xeNufdIZQy7GUlld74aEhnu0JC735J7nNytaa3D1v5eZiMj+Xm4Q8Puc5+LdZBBBhlkkLGwMkZriQGL7lmrN/wsJj1qypHEM+oWqZ/fFD8/LoVflgAAADLYLAEAAGSwWQIAAMhgswQAAJChIdE8/aJ1VDScPT/VxbxM7MPvhkLch75G7TXjrpFrqTs/FlyXdOJ9bou9xmdUExkrxK/DZbiGtNFExkqfIf5ebEY10bS23GXccffSNk8Z8WdKBhlkkEEGGfmMm4nv/dUu42JoMHVFH5p6MMTN25v1nqknyg8uhBAq0YUOvywBAABksFkCAADImNFmSVV7VPWyql5S1V5VfYuqvlNVv6yq11T111X1TbO1WAAAgBftuYdSquorItItImtDCN9W1U+LyIdE5P0iciSE0Keq/0FEflJEfi6XVZX1ckimhlIuEdtHdTAxm6pJ7N83d6vd9zWKfdFeiXuzWl1ut+vfanV7yZ5Ef1ezm8LY7YZktbl19CRaxFrclrXLDbZsc/e2L7GOFreOPYVdR+s8ZXSRQQYZZJBBxjNm7PcDJ0Wk0WUcCI9M3eCmVR8OtsdJRKTZfa9PyOLompSZ/hlukYgsVtVF8sYYzFER+QEROT55/lMi8sEZvgcAAMC8ee7NUgjhNRH5P0XkT+SNTdJdEbkgIt8MIbw+edlNEXkl9XpV/Yiqvqqqr357fPx5lwEAADCnnnuzpKotIvIBEXmniKwUkQYR6Zzu60MIR0MIlRBCZfHLLz/vMgAAAObUTB6ku1lEhkMI4yIiqvoZEdkkIs2qumjy16V3iMhrTwtqksvSKe2P6yPhkjm/SjdFr7kbzpl6o+409fGi39QbdEuU0VecMXW77DD1seKkPV/aGmX0FoPZjN6azejQeD/ZV5y217iMvppfx7ZExkA2w69jNjI66mQdZJBBBhlkLLAMjTP63fftWtll6oHihD2v26OMgXAqOjYdM+lZ+hMR+X5VXaKqKiLvE5ErIvLbIvLjk9d8WEQ+N4P3AAAAmFcz6Vn6srzRyP0VEbk4mXVURD4uIh9V1Wsi0iYiPz8L6wQAAJgXM/kznIQQflpEftodHhKR984kFwAAoF7MaLM0W+7LOrkapuYsuVEKMpKY2eDGKciVwh4ol3pNfS0x36jkfle77sY6lMv2RWPuPVIZw25GUtmdr4ZEhjs05O635B4nd2ta67C1v5fZyEh+Hu7QsPvc52IdZJBBBhlkLKyM0VpiwKJ71uoNP4tJj5pyJPGMukXq5zfFz49L4XEnAAAAGWyWAAAAMtgsAQAAZLBZAgAAyNCQaJ5+0ToqGs6en+piXib24XdDIe5DX6P2mnHXyLXUnR8Lrks68T63xV7jM6qJjBXi1+EyXEPaaCJjpc8Qfy82o5poWlvuMu64e2mbp4z4MyWDDDLIIIOMfMbNxPf+apdxMTSYuqIPTT0Y4ubtzXrP1BPlBxdCCJXoQodflgAAADLYLAEAAGSwWQIAAMioi6GUVVkvh2RqKOUSsX1UBxOzqZrE/n1zt9p9X6PYF+2VuDer1eV2u/6tVreX7En0dzW7KYzdbkhWm1tHT6JFrMVtWbvcYMs2d2/7EutocevYU9h1tM5TRhcZZJBBBhlkPGPGfj9wUkQaXcaB8MjUDW5a9eFge5xERJrd9/qELI6uSeGXJQAAgAw2SwAAABlslgAAADLqomepSS5Lp7Q/ro+ES+b8Kt0UveZuOGfqjbrT1MeLflNv0C1RRl9xxtTtssPUx4qT9nxpa5TRWwxmM3prNqNDOxPrOG2vcRl9Nb+ObYmMgWyGX8dsZHTUyTrIIIMMMshYYBkaZ/S779u1ssvUA8UJe163RxkD4VR0bDr4ZQkAACCDzRIAAEAGmyUAAICMuuhZui/r5GqYmrPkRinISGJmgxunIFcKe6Bc6jX1tcR8o5LbKl53Yx3KZfuiMfceqYxhNyOp7M5XQyLDHRpy91tyj5O7Na112Nrfy2xkJD8Pd2jYfe5zsQ4yyCCDDDIWVsZoLTFg0T1r9YafxaRHTTmSeEbdIvXzm+Lnx6XwyxIAAEAGmyUAAIAMNksAAAAZbJYAAAAyNCSap1+0joqGs+enupiXiX343VCI+9DXqL1m3DVyLXXnx4Lrkk68z22x1/iMaiJjhfh1uAzXkDaayFjpM8Tfi82oJprWlruMO+5e2uYpI/5MySCDDDLIICOfcTPxvb/aZVwMDaau6ENTD4a4eXuz3jP1RPnBhRBCJbrQ4ZclAACADDZLAAAAGWyWAAAAMupiKGVV1sshmRpKuURsH9XBxGyqJrF/39ytdt/XKPZFeyXuzWp1ud2uf6vV7SV7Ev1dzW4KY7cbktXm1tGTaBFrcVvWLjfYss3d277EOlrcOvYUdh2t85TRRQYZZJBBBhnPmLHfD5wUkUaXcSA8MnWDm1Z9ONgeJxGRZve9PiGLo2tS+GUJAAAgg80SAABABpslAACAjLroWWqSy9Ip7Y/rI+GSOb9KN0WvuRvOmXqj7jT18aLf1Bt0S5TRV5wxdbvsMPWx4qQ9X9oaZfQWg9mM3prN6NDOxDpO22tcRl/Nr2NbImMgm+HXMRsZHXWyDjLIIIMMMhZYhsYZ/e77dq3sMvVAccKe1+1RxkA4FR2bDn5ZAgAAyGCzBAAAkMFmCQAAIKMuepbuyzq5GqbmLLlRCjKSmNngxinIlcIeKJd6TX0tMd+o5LaK191Yh3LZvmjMvUcqY9jNSCq789WQyHCHhtz9ltzj5G5Nax229vcyGxnJz8MdGnaf+1ysgwwyyCCDjIWVMVpLDFh0z1q94Wcx6VFTjiSeUbdI/fym+PlxKfyyBAAAkMFmCQAAIIPNEgAAQAabJQAAgAwNiebpF62jouHs+aku5mViH343FOI+9DVqrxl3jVxL3fmx4LqkE+9zW+w1PqOayFghfh0uwzWkjSYyVvoM8fdiM6qJprXlLuOOu5e2ecqIP1MyyCCDDDLIyGfcTHzvr3YZF0ODqSv60NSDIW7e3qz3TD1RfnAhhFCJLnT4ZQkAACCDzRIAAEAGmyUAAICMuhhKWZX1ckimhlIuEdtHdTAxm6pJ7N83d6vd9zWKfdFeiXuzWl1ut+vfanV7yZ5Ef1ezm8LY7YZktbl19CRaxFrclrXLDbZsc/e2L7GOFreOPYVdR+s8ZXSRQQYZZJBBxjNm7PcDJ0Wk0WUcCI9M3eCmVR8OtsdJRKTZfa9PyOLomhR+WQIAAMhgswQAAJDBZgkAACCjLnqWmuSydEr74/pIuGTOr9JN0WvuhnOm3qg7TX286Df1Bt0SZfQVZ0zdLjtMfaw4ac+XtkYZvcVgNqO3ZjM6tDOxjtP2GpfRV/Pr2JbIGMhm+HXMRkZHnayDDDLIIIOMBZahcUa/+75dK7tMPVCcsOd1e5QxEE5Fx6aDX5YAAAAy2CwBAABksFkCAADIqIuepfuyTq6GqTlLbpSCjCRmNrhxCnKlsAfKpV5TX0vMNyq5reJ1N9ahXLYvGnPvkcoYdjOSyu58NSQy3KEhd78l9zi5W9Nah639vcxGRvLzcIeG3ec+F+sggwwyyCBjYWWM1hIDFt2zVm/4WUx61JQjiWfULVI/vyl+flwKvywBAABksFkCAADIYLMEAACQwWYJAAAgQ0OiefpF66hoOHt+qot5mdiH3w2FuA99jdprxl0j11J3fiy4LunE+9wWe43PqCYyVohfh8twDWmjiYyVPkP8vdiMaqJpbbnLuOPupW2eMuLPlAwyyCCDDDLyGTcT3/urXcbF0GDqij409WCIm7c36z1TT5QfXAghVKILHX5ZAgAAyGCzBAAAkMFmCQAAIKMuhlJWZb0ckqmhlEvE9lEdTMymahL7983davd9jWJftFfi3qxWl9vt+rda3V6yJ9Hf1eymMHa7IVltbh09iRaxFrdl7XKDLdvcve1LrKPFrWNPYdfROk8ZXWSQQQYZZJDxjBn7/cBJEWl0GQfCI1M3uGnVh4PtcRIRaXbf6xOyOLomhV+WAAAAMtgsAQAAZLBZAgAAyKiLnqUmuSyd0v64PhIumfOrdFP0mrvhnKk36k5THy/6Tb1Bt0QZfcUZU8D/LWUAABm2SURBVLfLDlMfK07a86WtUUZvMZjN6K3ZjA7tTKzjtL3GZfTV/Dq2JTIGshl+HbOR0VEn6yCDDDLIIGOBZWic0e++b9fKLlMPFCfsed0eZQyEU9Gx6eCXJQAAgAw2SwAAABlslgAAADLqomfpvqyTq2FqzpIbpSAjiZkNbpyCXCnsgXKp19TXEvONSm6reN2NdSiX7YvG3HukMobdjKSyO18NiQx3aMjdb8k9Tu7WtNZha38vs5GR/DzcoWH3uc/FOsgggwwyyFhYGaO1xIBF96zVG34Wkx415UjiGXWL1M9vip8fl8IvSwAAABlslgAAADLYLAEAAGSwWQIAAMjQkGieftE6KhrOnp/qYl4m9uF3QyHuQ1+j9ppx18i11J0fC65LOvE+t8Ve4zOqiYwV4tfhMlxD2mgiY6XPEH8vNqOaaFpb7jLuuHtpm6eM+DMlgwwyyCCDjHzGzcT3/mqXcTE0mLqiD009GOLm7c16z9QT5QcXQgiV6EKHX5YAAAAy2CwBAABkPHWzpKq/oKq3VPXSE8daVfVLqvrHk//ZMnlcVfXfqeo1Vf1DVX3PXC4eAABgrk1nKOUvicj/LSK//MSxT4jIb4UQPqmqn5isPy4i20Tkeyf/398WkZ+b/M+sqqyXQzI1lHKJ2D6qg4nZVE1i/765W+2+r1Hsi/ZK3JvV6nK7Xf9Wq9tL9iT6u5rdFMZuNySrza2jJ9Ei1uK2rF1usGWbu7d9iXW0uHXsKew6Wucpo4sMMsgggwwynjFjvx84KSKNLuNAeGTqBjet+nCwPU4iIs3ue31CFkfXpDz1l6UQwn8RkT91hz8gIp+a/O+fEpEPPnH8l8Mb/l8RaVbVFdNaCQAAQB163p6lZSGE0cn/XhWRZZP//RUR+cYT192cPBZR1Y+o6quq+uq3x8efcxkAAABza8YN3uGN2QPPPH8ghHA0hFAJIVQWv/zyTJcBAAAwJ573QbpjqroihDA6+We2W5PHXxORVU9c947JY1lNclk6pf1xfSRcMudX6aboNXfDOVNv1J2mPl70m3qDboky+oozpm6XHaY+Vpy050tbo4zeYjCb0VuzGR3amVjHaXuNy+ir+XVsS2QMZDP8OmYjo6NO1kEGGWSQQcYCy9A4o999366VXaYeKE7Y87o9yhgIp6Jj0/G8vyx9XkQ+PPnfPywin3vi+D+a/Fdx3y8id5/4cx0AAMBfOU/9ZUlVe0Xk74rIUlW9KSI/LSKfFJFPq+pPisgNEfmJycu/KCLvF5FrInJPRP7JHKwZAADghXnqZimEsOsvOfW+xLVBRP7pTBcFAABQL563Z2lW3Zd1cjVMzVlyoxRkJDGzwY1TkCuFPVAu9Zr6WqIFveT+CHndjXUol+2Lxtx7pDKG3YyksjtfDYkMd2jI3W/JPU7u1rTWYWt/L7ORkfw83KFh97nPxTrIIIMMMshYWBmjtcSARfes1Rt+FpMeNeVI4hl1i9TPb4qfH5fC404AAAAy2CwBAABksFkCAADIYLMEAACQoSHRPP2idVQ0nD0/1cW8TOzD74ZC3Ie+Ru01466Ra6k7PxZcl3TifW6LvcZnVBMZK8Svw2W4hrTRRMZKnyH+XmxGNdG0ttxl3HH30jZPGfFnSgYZZJBBBhn5jJuJ7/3VLuNiaDB1RR+aejDEzdub9Z6pJ8oPLoQQKtGFDr8sAQAAZLBZAgAAyGCzBAAAkFEXQymrsl4OydRQyiVi+6gOJmZTNYn9++Zutfu+RrEv2itxb1ary+12/Vutbi/Zk+jvanZTGLvdkKw2t46eRItYi9uydrnBlm3u3vYl1tHi1rGnsOtonaeMLjLIIIMMMsh4xoz9fuCkiDS6jAPhkakb3LTqw8H2OImINLvv9QlZHF2Twi9LAAAAGWyWAAAAMtgsAQAAZNRFz1KTXJZOaX9cHwmXzPlVuil6zd1wztQbdaepjxf9pt6gW6KMvuKMqdtlh6mPFSft+dLWKKO3GMxm9NZsRod2JtZx2l7jMvpqfh3bEhkD2Qy/jtnI6KiTdZBBBhlkkLHAMjTO6Hfft2tll6kHihP2vG6PMgbCqejYdPDLEgAAQAabJQAAgAw2SwAAABl10bN0X9bJ1TA1Z8mNUpCRxMwGN05BrhT2QLnUa+priflGJbdVvO7GOpTL9kVj7j1SGcNuRlLZna+GRIY7NOTut+QeJ3drWuuwtb+X2chIfh7u0LD73OdiHWSQQQYZZCysjNFaYsCie9bqDT+LSY+aciTxjLpF6uc3xc+PS+GXJQAAgAw2SwAAABlslgAAADLYLAEAAGRoSDRPv2gdFQ1nz091MS8T+/C7oRD3oa9Re824a+Ra6s6PBdclnXif22Kv8RnVRMYK8etwGa4hbTSRsdJniL8Xm1FNNK0tdxl33L20zVNG/JmSQQYZZJBBRj7jZuJ7f7XLuBgaTF3Rh6YeDHHz9ma9Z+qJ8oMLIYRKdKHDL0sAAAAZbJYAAAAy2CwBAABk1MVQyqqsl0MyNZRyidg+qoOJ2VRNYv++uVvtvq9R7Iv2Styb1epyu13/VqvbS/Yk+rua3RTGbjckq82toyfRItbitqxdbrBlm7u3fYl1tLh17CnsOlrnKaOLDDLIIIMMMp4xY78fOCkijS7jQHhk6gY3rfpwsD1OIiLN7nt9QhZH16TwyxIAAEAGmyUAAIAMNksAAAAZddGz1CSXpVPaH9dHwiVzfpVuil5zN5wz9UbdaerjRb+pN+iWKKOvOGPqdtlh6mPFSXu+tDXK6C0Gsxm9NZvRoZ2JdZy217iMvppfx7ZExkA2w69jNjI66mQdZJBBBhlkLLAMjTP63fftWtll6oHihD2v26OMgXAqOjYd/LIEAACQwWYJAAAgg80SAABARl30LN2XdXI1TM1ZcqMUZCQxs8GNU5ArhT1QLvWa+lpivlHJbRWvu7EO5bJ90Zh7j1TGsJuRVHbnqyGR4Q4NufstucfJ3ZrWOmzt72U2MpKfhzs07D73uVgHGWSQQQYZCytjtJYYsOietXrDz2LSo6YcSTyjbpH6+U3x8+NS+GUJAAAgg80SAABABpslAACADDZLAAAAGRoSzdMvWkdFw9nzU13My8Q+/G4oxH3oa9ReM+4auZa682PBdUkn3ue22Gt8RjWRsUL8OlyGa0gbTWSs9Bni78VmVBNNa8tdxh13L23zlBF/pmSQQQYZZJCRz7iZ+N5f7TIuhgZTV/ShqQdD3Ly9We+ZeqL84EIIoRJd6PDLEgAAQAabJQAAgAw2SwAAABl1MZSyKuvlkEwNpVwito/qYGI2VZPYv2/uVrvvaxT7or0S92a1utxu17/V6vaSPYn+rmY3hbHbDclqc+voSbSItbgta5cbbNnm7m1fYh0tbh17CruO1nnK6CKDDDLIIIOMZ8zY7wdOikijyzgQHpm6wU2rPhxsj5OISLP7Xp+QxdE1KfyyBAAAkMFmCQAAIIPNEgAAQEZd9Cw1yWXplPbH9ZFwyZxfpZui19wN50y9UXea+njRb+oNuiXK6CvOmLpddpj6WHHSni9tjTJ6i8FsRm/NZnRoZ2Idp+01LqOv5texLZExkM3w65iNjI46WQcZZJBBBhkLLEPjjH73fbtWdpl6oDhhz+v2KGMgnIqOTQe/LAEAAGSwWQIAAMhgswQAAJBRFz1L92WdXA1Tc5bcKAUZScxscOMU5EphD5RLvaa+lphvVHJbxeturEO5bF805t4jlTHsZiSV3flqSGS4Q0PufkvucXK3prUOW/t7mY2M5OfhDg27z30u1kEGGWSQQcbCyhitJQYsumet3vCzmPSoKUcSz6hbpH5+U/z8uBR+WQIAAMhgswQAAJDBZgkAACCDzRIAAECGhkTz9IvWUdFw9vxUF/MysQ+/GwpxH/oatdeMu0aupe78WHBd0on3uS32Gp9RTWSsEL8Ol+Ea0kYTGSt9hvh7sRnVRNPacpdxx91L2zxlxJ8pGWSQQQYZZOQzbia+91e7jIuhwdQVfWjqwRA3b2/We6aeKD+4EEKoRBc6/LIEAACQwWYJAAAgg80SAABARl0MpazKejkkU0Mpl4jtozqYmE3VJPbvm7vV7vsaxb5or8S9Wa0ut9v1b7W6vWRPor+r2U1h7HZDstrcOnoSLWItbsva5QZbtrl725dYR4tbx57CrqN1njK6yCCDDDLIIOMZM/b7gZMi0ugyDoRHpm5w06oPB9vjJCLS7L7XJ2RxdE0KvywBAABksFkCAADIYLME/H/t3X2wVdV9xvHvcy8vVZOAgNUItOjIxIIKxGsqIWlMYiMkKGaqqY6pJqaTcSaNxmkmE2pnMv3DPzLpaNtpzcSJxrQVaEBp0HpRqk51VIwaW+RNg+ALyFusIaYmGDi//nG2cNfam83lcuScwzyfGYf723uf56yzXHiW56y7tpmZWY2OWLM0ijXMZtq++uZYnZyfqFmlx+yKx5N6pi5N6iWNxUl9jj5VyljUeCCpp/HZpF7QWJqe77mglLGwcX9txsK9acZ0za5ox/L0mixj0d68HXMqMvprM/J2tCJjeoe0wxnOcIYznHGUZaicsTh7v53C5Und37grPa8LSxn9cU/p2GD4kyUzMzOzGp4smZmZmdXwZMnMzMysRkesWfoNU1kf+/dZyrZS4LWKPRuy7RRY20gP9PYsTOoNFfsb9WRTxRezbR16e9MHbc+eoypjU7ZHUm92fltUZGSHNmavtye7ndyOQbUjrfPX0oqMyv7IDm3K+v3daIcznOEMZzjj6MrYurdig8XsXqsv53sx6dakfK3iHnXDlO/fVL5/XBV/smRmZmZWw5MlMzMzsxqeLJmZmZnV8GTJzMzMrIaiYvH0kTa9T/HQU/tXMZ9IevO7jVFeh36a0mt2Zgu5xmXnt0e2SrrieX5Oek2esa0i4/3k7cgysgVpWysyTs4zyF9LmrGtYtHaSVnG69lrGdumjHKfOsMZznCGM5xRn7G54n1/UpbxXByX1H16O6nvj/Li7fP1VlK/2bv7mYjoK12Y8SdLZmZmZjUOOlmSdLukHZJWDzj2HUnrJa2StFTS6AHn5kvaIOl5SeX7g5iZmZl1kcF8snQHkN/QbAVwRkScBbwAzAeQNAW4DJhaPOYWSeXvnczMzMy6xEE3pYyIRyRNyo4NvAPtSuCS4ud5wKKI2A1skrQB+BDwRN1zbONsvs3+TSmPJV1HdWPF3lSjSL/fvEbpvO+9pA+6jvLarDFZ7rXZ+q0x2Vzy+or1XaOzXRivzTbJGpu14/qKJWLHZ1PWr2YbW47NXtvXKtpxfNaOv2ik7RjTpoyvOsMZznCGM5xxiBlfzzecBN6bZfx1/Dapj8t2q74p0jVOAKOz9/U3OaZ0TZVWrFm6GnjndsLjgVcHnNtcHDMzMzPrSoc1WZJ0A7AHuHMIj/2ypKclPf3rnTsPpxlmZmZm75ohT5YkfQGYC1wR+/cf2AJMHHDZhOJYSUTcGhF9EdF3zAknDLUZZmZmZu+qId1IV9Js4BvAxyJi4KYFy4AFkm4CTgYmw4DFSAcwijXMZtq++uZYnZyfqFmlx+yKx5N6pi5N6iWNxUl9jj5VyljUeCCpp/HZpF7QWJqe7yn/ct/Cxv21GQv3phnTla+Vh0WN5ek1WcaivXk75lRk9Cd1npG3oxUZ0zukHc5whjOc4YyjLEPljMXZ++0ULk/q/sZd6XldWMroj3tKxwbjoJMlSQuB84BxkjYD36L5228jgRVqLqhaGRHXRMQaST8C1tL8eu4rERUrrMzMzMy6xGB+G+7yisO31Vx/I3Dj4TTKzMzMrFN4B28zMzOzGkNas9Rqv2Yqq+PJffWwbP+j1yr2bOjNrlnXSOd9w3oWJPWLjfJmTcOU5m7MnmZ4T3pgW1VGds2mSK8Znt0bblujPD89WMawLGP7EDLydrQiYyiv5d1ohzOc4QxnOOPoythakdHbk67qeSnbi6lHtyT1lor7y43UnuzI+0rXVPEnS2ZmZmY1PFkyMzMzq+HJkpmZmVkNT5bMzMzMaigqFk8fadP6emL5U/sXYp1KugDrv2Nk6TFnk95Ab2O2Vn2S3k7qnzWGlzImZwu9NsaIpD41y3g+Ow9wev48WVsna3dSr614LVOyazZkz3Na9hzrB9GOF1vwWg7WjnUVGX/gDGc4wxnOcMZhZjwX5RvczsjeK1fEuKS+UL9K6h8wppRxJW8k9eu9bz4TEX2lCzP+ZMnMzMyshidLZmZmZjU8WTIzMzOr0RFrlk7qOzuueGr/ppT/Qtqmiyse00+6OdV50ZvUK5TOAz8e+UZU8KjSTbE+km1w9ZjSzI820vMA/9WTZnw0uxXe41k7ZjbK/f1Y1o5ZpM/zRNaOmVFux2PZ88wqtSPN+LAznOEMZzjDGR2aMbNRvq1s/l75h/wmqZ/N9o2eVvG+vyp7nk09Y7xmyczMzOxwebJkZmZmVsOTJTMzM7MaHXEj3VGs5dOcua/+XryQnP8AZ5ces4CfJvXHuCiplzaWJfVMPl7KuJdHk/qcmJPU98V9SX0W55czGg8l9Qw+k9T98R9JfWZFRn/8Z23G8rg3a8cfDyJjbnb+npZnnDmEjOXOcIYznOEMZxwkYyoXlDIe5OGkPpVLkvqJWJHUp1S876+MR0rHBsOfLJmZmZnV8GTJzMzMrIYnS2ZmZmY1OmLN0ltMYVWs3FcPy/ZKeKliL6jhSo/9pJHO+0Zk08D15W0fGJ7tZ7Qme94R2X5PL0Z2ATA8O7Qu219iZHZ+0xAyRmR7S2yM8hw3z1hfykjPDyWj/FqqMtI+W5/9u8vb4QxnOMMZznBGnvFSxRaQPdl79ivszs6nezNtqfg8aCT5ZOB3y09UwZ8smZmZmdXwZMnMzMyshidLZmZmZjU8WTIzMzOr0RELvN/D//BhTtxXR/wqOX9+jCk95l/5ZVJ/ifcl9eJ4I6k/z+hSxkJ2JfXVMS6p79brSf05xpYy7iJ9nj/jhKReRprxJ5Rfy1J+ntRXZgvOlrEzqS9VVUb6PFcpbcePSxnl15JnXOkMZzjDGc5wRhsyLtZJpYz7+N+k/iSnJ/XKLGMG40sZj/Fa6dhg+JMlMzMzsxqeLJmZmZnV8GTJzMzMrIaiYsPHI94IaSfwMjAOsgU8drjcp63nPm0992nruU9bz33aeu3u09+PiBMOdlFHTJbeIenpiOhrdzuOJu7T1nOftp77tPXcp63nPm29bulTfw1nZmZmVsOTJTMzM7ManTZZurXdDTgKuU9bz33aeu7T1nOftp77tPW6ok87as2SmZmZWafptE+WzMzMzDpKx0yWJM2W9LykDZK+2e72dCNJEyU9LGmtpDWSriuOj5G0QtLPij+Pb3dbu4mkXknPSrq3qE+R9GQxVv9N0oh2t7HbSBotaYmk9ZLWSZrpcTp0kq4v/s6vlrRQ0u94nB46SbdL2iFp9YBjleNSTf9Q9O8qSR9sX8s71wH69DvF3/1VkpZKGj3g3PyiT5+XdEF7Wl3WEZMlSb3APwFzgCnA5ZKmtLdVXWkP8JcRMQU4F/hK0Y/fBB6MiMnAg0Vtg3cdsG5A/W3g5og4DXgD+FJbWtXd/h5YHhGnA9No9q/H6RBIGg9cC/RFxBlAL3AZHqdDcQcwOzt2oHE5B5hc/PNl4LtHqI3d5g7KfboCOCMizgJeAOYDFO9XlwFTi8fcUswP2q4jJkvAh4ANEbExIt4GFgHz2tymrhMRWyPip8XPb9J8AxpPsy9/WFz2Q+Di9rSw+0iaAHwG+H5RC/gEsKS4xP15iCSNAv4IuA0gIt6OiF/gcXo4hgHHSBoGHAtsxeP0kEXEI5DdrfXA43Ie8M/RtBIYLen9R6al3aOqTyPigYjYU5QrgQnFz/OARRGxOyI2ARtozg/arlMmS+OBVwfUm4tjNkSSJgEzgCeBEyNia3FqG3Bim5rVjf4O+AbQKOqxwC8G/EX3WD10pwA7gR8UX29+X9JxeJwOSURsAf4WeIXmJGkX8Awep61yoHHp963WuBroL37u2D7tlMmStZCk9wB3AV+LiF8OPBfNX3/0r0AOgqS5wI6IeKbdbTnKDAM+CHw3ImYA/0f2lZvH6eAVa2jm0ZyEngwcR/lrD2sBj8vWknQDzeUjd7a7LQfTKZOlLcDEAfWE4pgdIknDaU6U7oyIu4vD29/5eLj4c0e72tdlZgEXSXqJ5lfDn6C51mZ08XUHeKwOxWZgc0Q8WdRLaE6ePE6H5nxgU0TsjIjfAnfTHLsep61xoHHp963DIOkLwFzgiti/h1HH9mmnTJaeAiYXv70xguYCr2VtblPXKdbT3Aasi4ibBpxaBlxV/HwV8OMj3bZuFBHzI2JCREyiOSYfiogrgIeBS4rL3J+HKCK2Aa9K+kBx6JPAWjxOh+oV4FxJxxb/DXinPz1OW+NA43IZcGXxW3HnArsGfF1nNSTNprm84aKIeGvAqWXAZZJGSjqF5uL5n7SjjbmO2ZRS0qdprg/pBW6PiBvb3KSuI+kjwKPAc+xfY/NXNNct/Qj4PeBl4HMRkS9itBqSzgO+HhFzJZ1K85OmMcCzwOcjYnc729dtJE2nuWh+BLAR+CLN/3nzOB0CSX8D/CnNrzSeBf6c5loPj9NDIGkhcB4wDtgOfAv4dyrGZTEx/UeaX3m+BXwxIp5uR7s72QH6dD4wEni9uGxlRFxTXH8DzXVMe2guJenPM9uhYyZLZmZmZp2oU76GMzMzM+tIniyZmZmZ1fBkyczMzKyGJ0tmZmZmNTxZMjMzM6vhyZKZmZlZDU+WzMzMzGp4smRmZmZW4/8BAWwOAkwgU5AAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 720x720 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "fig, ax = plt.subplots(figsize=(10,10))\n",
    "ax.imshow(v)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [],
   "source": [
    " loss_g = criterion(D(generated),valid)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Variable containing:\n",
       " 0.7115\n",
       "[torch.cuda.FloatTensor of size 1 (GPU 0)]"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "loss_g"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "loss_d_real = criterion(D(input_img),valid)\n",
    "loss_d_fake = criterion(D(generated),fake)\n",
    "loss_d = 0.5 * (loss_d_real + loss_d_fake)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Variable containing:\n",
       " 0.7198\n",
       "[torch.cuda.FloatTensor of size 1 (GPU 0)]"
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "loss_d_real"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Variable containing:\n",
       " 0.7140\n",
       "[torch.cuda.FloatTensor of size 1 (GPU 0)]"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "loss_d_fake"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Variable containing:\n",
       " 0.7169\n",
       "[torch.cuda.FloatTensor of size 1 (GPU 0)]"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "loss_d"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "'method' object is not iterable",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-22-0ce367339244>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     94\u001b[0m         \u001b[0mPieceGenerator\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0midn\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     95\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 96\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mJigsaw\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpuzzle_board\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m<ipython-input-22-0ce367339244>\u001b[0m in \u001b[0;36m__repr__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     49\u001b[0m         \u001b[0mReturns\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mstring\u001b[0m \u001b[0mrepresentation\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     50\u001b[0m         \"\"\"\n\u001b[0;32m---> 51\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     52\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     53\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mpuzzle_board\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-22-0ce367339244>\u001b[0m in \u001b[0;36m__str__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     20\u001b[0m         \u001b[0;32mfor\u001b[0m \u001b[0mrow\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpieces\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     21\u001b[0m         \u001b[0;31m#print(row)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 22\u001b[0;31m             \u001b[0;32mfor\u001b[0m \u001b[0mcol\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrow\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     23\u001b[0m                \u001b[0;31m#print(col)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     24\u001b[0m                 \u001b[0md\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0md\u001b[0m \u001b[0;34m+\u001b[0m\u001b[0;34m\" \"\u001b[0m\u001b[0;34m+\u001b[0m \u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcol\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: 'method' object is not iterable"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "input_img = Tensor(batch_size,3,img_x,img_y)\n",
    "valid = Variable(Tensor(np.ones(patch)), requires_grad=False)\n",
    "fake = Variable(Tensor(np.zeros(patch)), requires_grad=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 57,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "0 % 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
